# Generated by Django 2.2.10 on 2021-01-06 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='special_offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='kitchen/')),
                ('price', models.CharField(max_length=10)),
                ('discount_price', models.CharField(max_length=10)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='other.Offer')),
            ],
        ),
    ]
