# Generated by Django 2.2.10 on 2021-01-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_offer',
            name='detail',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='special_offer',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
