# Generated by Django 2.2.10 on 2021-01-09 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_breakfast_cereal_fruits_vegetables_home_snacks_staples'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast_cereal',
            name='detail',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fruits_vegetables',
            name='detail',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snacks',
            name='detail',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staples',
            name='detail',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='breakfast_cereal',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='breakfast_cereal',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.Home'),
        ),
        migrations.AlterField(
            model_name='fruits_vegetables',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fruits_vegetables',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.Home'),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.Home'),
        ),
        migrations.AlterField(
            model_name='staples',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
