# Generated by Django 2.2.10 on 2021-01-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0002_popular1_popular2_popular3'),
    ]

    operations = [
        migrations.AddField(
            model_name='clean_accesory',
            name='detail',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clean_accesory',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
