# Generated by Django 2.2.10 on 2021-01-05 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_name', models.CharField(max_length=50)),
                ('kitchen_pic', models.ImageField(upload_to='kitchen/')),
                ('kitchen_price', models.CharField(max_length=10)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kitchen.Category1')),
            ],
        ),
    ]
