# Generated by Django 2.2.10 on 2021-01-07 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_auto_20210106_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kitchen/popular/')),
                ('item', models.CharField(max_length=50)),
                ('caption', models.CharField(max_length=20)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kitchen.Category1')),
            ],
        ),
    ]
